### ISSUE TITLE
특수 문자가 포함된 트윗이 업로드 되지 않는 현상

### ISSUE THREAD

**Issue by SasarinoMARi** [RyuaNerin/StreamingRespirator#2]
느낌표나 소괄호, 온점, 반점, 세미콜론, 등 일부 문자가 포함된 트윗을 보내려는 경우 업로드 되지 않는 문제가 발생하는 듯
항상 안되는건 아니고 간헐적으로 발생하는 문제로 보임

특정 트윗에 관심글이 되지 않는 문제도 있는데 같은 문제인지는 확인이 필요함

**Comment by RyuaNerin** [comment]
Custom Via 쓰시죠?

**Comment by RyuaNerin** [comment]
custom via for azurea 사용중이면 [최신 릴리즈](https://github.com/RyuaNerin/CustomViaForAzurea/blob/master/AzureaCustomVia.js)로 패치하면 해결 가능

**Comment by Assize** [comment]
아이고 그것때문이었나보구나 생사람 잡고 있었네......

**Comment by SasarinoMARi** [comment]
아이고 그것때문이어쑥나 생사람 잡고 있었네

**Comment by RyuaNerin** [comment]
https://github.com/RyuaNerin/CustomViaForAzurea/blob/master/AzureaCustomVia.js#L6

이게 호흡기때문에 패치한거야ㅋㅋㅋㅋ
