### ISSUE TITLE
앱과 프록시간 HTTP로 통신할 수 있는 옵션도 필요할 것 같아요.

### ISSUE THREAD

**Issue by unstabler** [RyuaNerin/StreamingRespirator#4]
> https://m6n.onsen.tech/@tmyt/102788204497890980
> > Azurea에 스트리밍을 에뮬레이션 하는 프록시를 붙여서 계속 사용하는 사람도 있습니다
> 
> 충격적인 사실이다..

> https://m6n.onsen.tech/@tmyt/102788217524402514
> 한국의 Azurea 커뮤니티 개 쩔어

> https://m6n.onsen.tech/@tmyt/102788208317438604
> 그 프록시 나도 가지고 싶다

> https://m6n.onsen.tech/@tmyt/102788225597814164
> 이거, 구조 상 HTTPS 인증서를 bypass 해서 조금 좋지 않은 느낌이 되니까 본체 쪽에서 조금 짐을 덜어줄까나

> https://m6n.onsen.tech/@tmyt/102788235828787868
> 정말로 멋진 것을 구현해 주셨으니까, 서드 파티 인증서를 신뢰하는 등의 리스크를 지지 않고도 해결될 수 있게 되면 행복할거야

> https://m6n.onsen.tech/@tmyt/102788239923818675
> proxy에 HTTP 리퀘스트를 쓰도록 할 테니까, 그 앞단만 HTTPS로 다시 감싸주면 될려나

> https://m6n.onsen.tech/@tmyt/102788263521321668
> 이 사람에게 연락하고 싶다, 영어가 좋을까, 일본어로 해도 양해를 구할 수 있을까, 참고로 한국어는 낙제입니다

안녕하세요!

Azurea 개발자님이 나중에 프록시 설정 시 plain HTTP로 통신하는 옵션을 구현하신다고 하는 것 같아요.
혹시 Azurea에 해당 옵션이 추가되면 Azurea-프록시 간의 통신을 자가 서명 HTTPS 대신 plain HTTP를 사용하는 옵션을 구현해 주실 수 있으신가요?

감사합니다!

**Comment by unstabler** [comment]
@tmyt

**Comment by RyuaNerin** [comment]
소중한 의견 감사합니다.

**Comment by tmyt** [comment]
Hello!

I am planning a new implementation that accepts the "http:" prefix in the proxy URL. (Example: "http:127.0.0.1")
If the proxy URL starts with the “http:” prefix, Azurea will send the request in clear text.
What do you think about this implementation?

**Comment by RyuaNerin** [comment]
hello.
I think there might be a link that only supports https, not supports both http and https.
so, it would be fine if call only `api.twitter.com` by http.
[Core/Streaming/RespiratorServer.cs#L200-L205](https://github.com/RyuaNerin/StreamingRespirator/blob/master/StreamingRespirator/Core/Streaming/RespiratorServer.cs#L200-L205)

**Comment by RyuaNerin** [comment]
f336fb160437d6269149586baed101e458101542

Streaming Respirator has been changed to process MITM on specified hosts only.
- `userstream.twitter.com`
- `api.twitter.com`

The CA private key has been encrypted, and the host in the server certificate bas been specified. so i think it will be relatively safer against malicious MITM attacks.
