### ISSUE TITLE
트위터 최소 브라우저 지원 변경으로 스트리밍 호흡기 로그인 불가

### ISSUE THREAD

**Issue by RyuaNerin** [RyuaNerin/StreamingRespirator#9]

**Comment by RyuaNerin** [comment]
일단 모바일 페이지로...

**Comment by Lastorder-DC** [comment]
모바일 페이지도 막혔습니다. 이제 로그인 자체가 안됩니다.

CefSharp 같은걸로 바꾸시는게..

**Comment by RyuaNerin** [comment]
@Lastorder-DC 새로운 방안을 고려해보겠습니다. 로그인 하겠다고 CefSharp 올리면, 호흡기는 2MiB 인데 Cef 에만 100 MiB 이상 쓰는게 배보다 배꼽이 커져버리는 꼴이 되버리는 것 같아 고민입니다.

**Comment by RyuaNerin** [comment]
윈도우10 내장 Edge 컨트롤을 사용한 방식으로 수정해볼 예정입니다.

**Comment by RyuaNerin** [comment]
브라우저에서 쿠키를 가져오는 방식으로 변경 669a8561df5898507d70ab843ab5e3bcca5fc57e
